#!/bin/bash
# 原作者：20th
# 原脚本连接: https://github.com/clcc2019/install_python3/blob/master/py.sh

# 默认安装 Python 3.8.2 版本
version = "3.8.2"
echo "自动安装 Python3.x 程序开始......"

#安装环境包
yum -y install zlib zlib-devel bzip2 bzip2-devel ncurses ncurses-devel readline readline-devel openssl openssl-devel openssl-static xz lzma xz-devel sqlite sqlite-devel
yum -y install gdbm gdbm-devel
yum -y install tk tk-devel
yum -y install libffi libffi-devel
yum -y install zlib* libffi-devel
yum install gcc* glien* -y
wget https://www.python.org/ftp/python/$version/Python-$version.tgz
tar -xvf Python-$version.tgz && mkdir /usr/local/python3 && cd Python-$version
./configure --prefix=/usr/local/python3 && make && make install
if test $[python3 -V]==0; then echo '安装成功'; else echo'安装出错！';fi
ln -f /usr/local/python3/bin/python3.8 /usr/bin/python3
ln -f /usr/local/python3/bin/pip3.8 /usr/bin/pip3
PATH=$PATH:/usr/bin/python3
echo '安装完成'
read -p '回车查看版本' V
python3 -V