# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    # The type of runner that the job will run on
    name: deploy to staging
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Hub Mirror Action.
        # You may pin to the exact commit or the version.
        # uses: Yikun/hub-mirror-action@132b206a796926508b73fe82e9f3bb0969a3add6
        uses: Yikun/hub-mirror-action@v1.1
        with:
          # The private SSH key which is used to to push code in destination hub.
          dst_key: MIIEogIBAAKCAQEAxS6FxE9In2ND2qgaXDwc1om5AXBB2HNbkNT/mRWT8Q6/hKf4ZrBQ/nx1N7Pq6yVtA71pwdc6XZ9YOZuMipPUnPnPXovaVRMVZw2BDhSzf45HyD8DCjcFUlj140vMfviTYHeqaxbFVDflRe0koVTbUqk+7UuFvNGkpCwcHCF83/Ar6tsYKxUjkznxoBmJ1vuDSVoBdM3Qt2WO640zCkJpnTQ+Tf3bhcZykxj03kvqbMyB8cObjkJHGBaAklIxk0XP4248O/sqYnbrjHGYAIUQaPzd2qBXpiFAarmxNZrLndj6hsjoQSbm0UkLSRB6narY5DQr9zxrFUs+dDa9Eeiy9wIDAQABAoIBABXfkUszmFTGCDLrTvFIYdKSuIkmUMeYFGI+npP2xtCI2En48B9EE9gHKmGhfb/UCQHPMzoji//yuzC4xqBgwccgFxbf4LprQYaLAvPy6+6Mc/4Mr2Okstxtrekm8WpsXLzoyWjTv9QV10MoiVW0OhgzWh2ssQs/Hkpv8jZUqKuWoOj2yCqtoAQwRaXvqQ8xYykCwh66wD1nvSbOHhN9t0m5otPR+4d1IUctCM5b/5UbDkwN7nDHpHaoUWk5KjuuyHa3pndfy3pILsnOoD2UDu7JD63KEnpq7euoZLqwrLBGuJyjVc0GSqj64jvXUxniyY37CL7Zn9hBL6vsnpcSJdECgYEA8uP45t1bn0PyYQHYLSzq3Aff2w6P3n2wM4RMeE5RLZUKZrORd4uEykwWKd8sK69rzRFSYrgtL+v3Y+vp5sGpS7qoVirY8+DtaFRJlM7rrtIz69phh4NKpPXOpqyFbf121td+B7s+Q+/nMhaeFr230AYBAGCGlJN3T75CxQD9FEMCgYEAz9L9emzcSHQsPsZ+PuoRIkbVGeGrNr6smsSX9OuO0kVm4eeVDKsk98ctDKfEVWnUXiSJXGBlnVL4KegGRyB0BBI7ih/X9BdYmVVnZQJDF0JqEIk7xnhtYNdc+jqUOb74Hcqeq0SexSIewn6F3XVl63keBEt7XAo1H541hJPjNT0CgYB9JGQLXqVkK3fn7zFYJTpkX1JA5QHPGmb8Q/+6RG+i0pVnUMF0HFgwen8415lEcL9UCsatwkLV2/e8bcI3eDQnpmYw7yaUkKEBDdxTZUEc84R40i1JyqVc1KDCU0Tz5JGkI6b1iM2N5z7xGaIeCWV5Mn61mQX96vSgC2EPa3D5TQKBgC/lcIXGkP4hyBCvrmjRiSFdMb/FQrBbQWxp4puPrlrHo+5scO16hAqW3MsN3zHQMiGASigAD2sys/70en3p/NLzYMV0kVCwELtF845T9yJlLAyjlCMpnguzlroUxhSI7qXvDKJsLitAsdYhUri3VcXvI/vZaZTMxXGEBNGJQ9QBAoGAT+EXaEL7Z+cH/av7enWKmQtvTsLPnwBGBFeV+enThMcWHCYYtYcToimpWUyoT+rYDYDg7UQORLItlv97pe4pEI08ucFQIU/ZG74UeiHovG9QK4QRJEHx2fMU2MfUazEh6PdZw5B6gpFx+fi49daIRYMDSu2PMViA43dn73eqY6A=
          # The app token which is used to  create repo in destination hub.
          dst_token: 012c3230cc4dfd59d2281001a609a396
          # Destination name. Such as `gitee/kunpengcompute`.
          dst: gitee/senjianlu
          # Source name. Such as `github/kunpengcompute`.
          src: github/senjianlu
